### ISSUE TITLE
windows run error

### ISSUE THREAD

**Issue by xzzh999** [deepmind/learning-to-learn#23]
Hi~

Great work! 

When i run pyinstaller on windows 7 64bit system, it comes some error:

	$ pyinstaller
	Traceback (most recent call last):
	  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
		"__main__", fname, loader, pkg_name)
	  File "c:\python27\lib\runpy.py", line 72, in _run_code
		exec code in run_globals
	  File "C:\Python27\Scripts\pyinstaller.exe\__main__.py", line 5, in <module>
	  File "c:\python27\lib\site-packages\PyInstaller\__init__.py", line 72, in <module>
		DEFAULT_SPECPATH = compat.getcwd()
	  File "c:\python27\lib\site-packages\PyInstaller\compat.py", line 613, in getcwd
		cwd = win32api.GetShortPathName(cwd)
	AttributeError: 'module' object has no attribute 'GetShortPathName'

here is the env:

       Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)] on win32

       Windows 7 x64 bit 

I have pywin32 and pypiwin32 both installed.

need u help, thank you.

**Comment by SaltOfTheFlame** [comment]
how did you fix this? I have same issue

**Comment by cooktea** [comment]
me too

**Comment by SaltOfTheFlame** [comment]
I have that issue on win10 x64

**Comment by vladiks** [comment]
Same issue. Python 2.7 64bit on Windows 10 64 bit.

**Comment by wdchui** [comment]
same isssue, the reason is that my path has chinese characters
