### ISSUE TITLE
TypeError when trying with latest Tensorflow

### ISSUE THREAD

**Issue by feiga** [deepmind/learning-to-learn#5]
When I try to play the code, error occurs, **TypeError: Expected int32, got list containing Tensors of type '_Message' instead.** Do you have any ideas about the error? Thanks a lot.

```
python train.py --problem=mnist --save_path=./mnist
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcublas.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcurand.so.7.5 locally
Extracting MNIST-data/train-images-idx3-ubyte.gz
Extracting MNIST-data/train-labels-idx1-ubyte.gz
Extracting MNIST-data/t10k-images-idx3-ubyte.gz
Extracting MNIST-data/t10k-labels-idx1-ubyte.gz
Optimizee variables
[u'mlp/linear_0/w:0', u'mlp/linear_0/b:0', u'mlp/linear_1/w:0', u'mlp/linear_1/b:0']
Problem variables
[]
Traceback (most recent call last):
  File "train.py", line 115, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 68, in main
    second_derivatives=FLAGS.second_derivatives)
  File "/home/feigao/exp/learning-to-learn/meta.py", line 398, in meta_minimize
    info = self.meta_loss(make_loss, len_unroll, **kwargs)
  File "/home/feigao/exp/learning-to-learn/meta.py", line 357, in meta_loss
    name="unroll")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2622, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2455, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2405, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/feigao/exp/learning-to-learn/meta.py", line 337, in time_step
    deltas, s_i_next = update(nets[key], fx, x_i, s_i)
  File "/home/feigao/exp/learning-to-learn/meta.py", line 320, in update
    deltas, state_next = zip(*[net(g, s) for g, s in zip(gradients, state)])
  File "/home/feigao/exp/learning-to-learn/nn/base.py", line 142, in __call__
    out = self._template(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/template.py", line 266, in __call__
    return self._call_func(args, kwargs, check_for_new_variables=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/template.py", line 215, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/feigao/exp/learning-to-learn/networks.py", line 249, in _build
    output, next_state = build_fn(reshaped_inputs, prev_state)
  File "/home/feigao/exp/learning-to-learn/networks.py", line 209, in _build
    inputs = self._preprocess(tf.expand_dims(inputs, -1))
  File "/home/feigao/exp/learning-to-learn/nn/base.py", line 142, in __call__
    out = self._template(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/template.py", line 266, in __call__
    return self._call_func(args, kwargs, check_for_new_variables=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/template.py", line 215, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/feigao/exp/learning-to-learn/preprocess.py", line 71, in _build
    return tf.concat_v2(ndims - 1, [clamped_log, sign])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1057, in concat_v2
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 651, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 716, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

originally defined at:
  File "/home/feigao/exp/learning-to-learn/meta.py", line 291, in meta_loss
    nets, net_keys, subsets = _make_nets(x, self._config, net_assignments)
  File "/home/feigao/exp/learning-to-learn/meta.py", line 186, in _make_nets
    net = networks.factory(**kwargs)
  File "/home/feigao/exp/learning-to-learn/networks.py", line 44, in factory
    return net_class(**net_options)
  File "/home/feigao/exp/learning-to-learn/networks.py", line 230, in __init__
    super(CoordinateWiseDeepLSTM, self).__init__(1, name=name, **kwargs)
  File "/home/feigao/exp/learning-to-learn/networks.py", line 181, in __init__
    self._preprocess = preprocess_class(**preprocess_options)
  File "/home/feigao/exp/learning-to-learn/preprocess.py", line 50, in __init__
    super(LogAndSign, self).__init__(name=name)
  File "/home/feigao/exp/learning-to-learn/nn/base.py", line 123, in __init__
    create_scope_now_=True)


originally defined at:
  File "/home/feigao/exp/learning-to-learn/meta.py", line 291, in meta_loss
    nets, net_keys, subsets = _make_nets(x, self._config, net_assignments)
  File "/home/feigao/exp/learning-to-learn/meta.py", line 186, in _make_nets
    net = networks.factory(**kwargs)
  File "/home/feigao/exp/learning-to-learn/networks.py", line 44, in factory
    return net_class(**net_options)
  File "/home/feigao/exp/learning-to-learn/networks.py", line 230, in __init__
    super(CoordinateWiseDeepLSTM, self).__init__(1, name=name, **kwargs)
  File "/home/feigao/exp/learning-to-learn/networks.py", line 174, in __init__
    super(StandardDeepLSTM, self).__init__(name)
  File "/home/feigao/exp/learning-to-learn/nn/base.py", line 123, in __init__
    create_scope_now_=True)
```

**Comment by feiga** [comment]
I tried with Tensorflow release v0.12 and it works.
