### ISSUE TITLE
AttributeError: module 'types' has no attribute 'StringTypes'

### ISSUE THREAD

**Issue by amiltonwong** [deepmind/learning-to-learn#8]
Hi, all,

I got the following running error

```
(root) root@milton-OptiPlex-9010:/data/code/learning-to-learn# python train.py --problem=mnist --save_path=./mnist
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting MNIST-data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting MNIST-data/train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting MNIST-data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting MNIST-data/t10k-labels-idx1-ubyte.gz
Traceback (most recent call last):
  File "train.py", line 115, in <module>
    tf.app.run()
  File "/root/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "train.py", line 60, in main
    problem, net_config, net_assignments = util.get_config(FLAGS.problem)
  File "/data/code/learning-to-learn/util.py", line 96, in get_config
    problem = problems.mnist(layers=(20,), mode=mode)
  File "/data/code/learning-to-learn/problems.py", line 164, in mnist
    initializers=_nn_initializers)
  File "/data/code/learning-to-learn/nn/mlp.py", line 64, in __init__
    super(MLP, self).__init__(name=name)
  File "/data/code/learning-to-learn/nn/base.py", line 119, in __init__
    if not isinstance(name, types.StringTypes):
AttributeError: module 'types' has no attribute 'StringTypes'

```

My environment is : tf 0.12.1, python 3.5.2
Any suggestion to fix it?

THANKS!

**Comment by normanheckscher** [comment]
Check your version. 
Same issue https://github.com/deepmind/learning-to-learn/issues/10

**Comment by sergomezcol** [comment]
This was actually a Python 2 vs 3 problem, nothing to do with TensorFlow. Thanks for raising the issue.

**Comment by sebastianruder** [comment]
I'm using `tensorflow==1.0.0rc2` but this error still occurs. Seems like it's more of a Python2 vs. Python3 issue, e.g. see [here](https://github.com/mk-fg/layered-yaml-attrdict-config/issues/4).
A fix that is independent of the Python version can be found [here](https://stackoverflow.com/questions/4232111/stringtype-and-nonetype-in-python3-x).
